#include <stdlib.h>
#include <dos.h>
#include <conio.h>
#include "ns_dpmi.h"
#include "ns_task.h"
#include "ns_cards.h"
#include "ns_user.h"
#include "ns_cms.h"

#include "m_misc.h"

#include "doomstat.h"

#include "i_debug.h"

static int CMS_Installed = 0;

static char *CMS_BufferStart;
static char *CMS_BufferEnd;
static char *CMS_CurrentBuffer;
static int CMS_BufferNum = 0;
static int CMS_NumBuffers = 0;
static int CMS_TotalBufferSize = 0;
static int CMS_TransferLength = 0;
static int CMS_CurrentLength = 0;

static char *CMS_SoundPtr;
volatile int CMS_SoundPlaying;

static task *CMS_Timer;

void (*CMS_CallBack)(void);

static void CMS_SetRegister(unsigned short regAddr, unsigned char reg, unsigned char val)
{
    outp(regAddr + 1, reg); /* Select the register */
    outp(regAddr, val);     /* Set the value of the register */

    //if (val != )
    //I_Printf("Addr: %u, Reg: %u, Val: %u\n", regAddr, reg, val);
}

/*---------------------------------------------------------------------
   Function: CMS_ServiceInterrupt

   Handles interrupt generated by sound card at the end of a voice
   transfer.  Calls the user supplied callback function.
---------------------------------------------------------------------*/

static void CMS_ServiceInterrupt(task *Task)
{
    unsigned short port = 0x220;

    unsigned char value;

    unsigned char value0;
    unsigned char value1;

    if (*CMS_SoundPtr < 0)
        value = *CMS_SoundPtr + 256;
    else
        value = *CMS_SoundPtr;

    value = value / 16;

    value0 = value;
    value0 = value0 << 1;
    value0 = value0 & 0xF;
    value0 = (value0 << 4) | value0;

    value0 = 0xFF;

    CMS_SetRegister(port, 0x02, value0);

    value1 = value;

    if (value1 != 8)
    {
        value1 = 0xEE;
    }

    CMS_SetRegister(port, 0x05, value1);

    CMS_SoundPtr++;

    CMS_CurrentLength--;
    if (CMS_CurrentLength == 0)
    {
        // Keep track of current buffer
        CMS_CurrentBuffer += CMS_TransferLength;
        CMS_BufferNum++;
        if (CMS_BufferNum >= CMS_NumBuffers)
        {
            CMS_BufferNum = 0;
            CMS_CurrentBuffer = CMS_BufferStart;
        }

        CMS_CurrentLength = CMS_TransferLength;
        CMS_SoundPtr = CMS_CurrentBuffer;

        // Call the caller's callback function
        if (CMS_CallBack != NULL)
        {
            CMS_CallBack();
        }
    }
}

/*---------------------------------------------------------------------
   Function: CMS_StopPlayback

   Ends the transfer of digitized sound to the Sound Source.
---------------------------------------------------------------------*/

void CMS_StopPlayback(void)
{
    if (CMS_SoundPlaying)
    {
        // Turn off
        //outp(0x61, inp(0x61) & 0xfc);
        TS_Terminate(CMS_Timer);
        CMS_SoundPlaying = 0;
        CMS_BufferStart = NULL;
    }
}

/*---------------------------------------------------------------------
   Function: CMS_BeginBufferedPlayback

   Begins multibuffered playback of digitized sound on the Sound Source.
---------------------------------------------------------------------*/

int CMS_BeginBufferedPlayback(
    char *BufferStart,
    int BufferSize,
    int NumDivisions,
    void (*CallBackFunc)(void))
{
    if (CMS_SoundPlaying)
    {
        CMS_StopPlayback();
    }

    CMS_SetCallBack(CallBackFunc);

    CMS_BufferStart = BufferStart;
    CMS_CurrentBuffer = BufferStart;
    CMS_SoundPtr = BufferStart;
    CMS_TotalBufferSize = BufferSize;
    CMS_BufferEnd = BufferStart + BufferSize;
    // VITI95: OPTIMIZE
    CMS_TransferLength = BufferSize / NumDivisions;
    CMS_CurrentLength = CMS_TransferLength;
    CMS_BufferNum = 0;
    CMS_NumBuffers = NumDivisions;

    CMS_SoundPlaying = 1;

    CMS_Timer = TS_ScheduleTask(CMS_ServiceInterrupt, CMS_SampleRate, 1, NULL);
    TS_Dispatch();

    return (CMS_Ok);
}

/*---------------------------------------------------------------------
   Function: CMS_SetCallBack

   Specifies the user function to call at the end of a sound transfer.
---------------------------------------------------------------------*/

void CMS_SetCallBack(void (*func)(void))
{
    CMS_CallBack = func;
}

/*---------------------------------------------------------------------
   Function: CMS_Init

   Initializes the Sound Source prepares the module to play digitized
   sounds.
---------------------------------------------------------------------*/

int CMS_Init(int soundcard)
{
    int status;
    int reg;
    unsigned short port = 0x220;

    if (CMS_Installed)
    {
        CMS_Shutdown();
    }

    /* Voice 1-6 registers */
    for (reg = 0; reg < 0x20; reg++) /* Loop through all registers */
    {
        CMS_SetRegister(port, reg, 0x0); /*  Zero the register */
    }
    CMS_SetRegister(port, 0x1C, 0x2); /* Set the Reset bit (RST) */

    CMS_SetRegister(port, 0x1C, 0x1); // Enable sound

    CMS_SetRegister(port, 0x18, 0x82); // Envelope generator 0
    CMS_SetRegister(port, 0x19, 0x82); // Envelope generator 1


    /* Voice 7-C registers */
    for (reg = 0; reg < 0x20; reg++) /* Loop through all registers */
    {
        CMS_SetRegister(port + 2, reg, 0x0); /*  Zero the register */
    }
    CMS_SetRegister(port + 2, 0x1C, 0x2); /* Set the Reset bit (RST) */

    CMS_SetRegister(port + 2, 0x1C, 0x1); // Enable sound

    CMS_SetRegister(port + 2, 0x18, 0x82); // Envelope generator 0
    CMS_SetRegister(port + 2, 0x19, 0x82); // Envelope generator 1

    status = CMS_Ok;

    CMS_SoundPlaying = 0;

    CMS_SetCallBack(NULL);

    CMS_BufferStart = NULL;

    CMS_Installed = 1;

    return (status);
}

int CMS_SetMixMode(int mode)
{
    mode = MONO_8BIT;
    return (mode);
}

/*---------------------------------------------------------------------
   Function: CMS_Shutdown

   Ends transfer of sound data to the Sound Source.
---------------------------------------------------------------------*/

void CMS_Shutdown(void)
{
    CMS_StopPlayback();

    CMS_SoundPlaying = 0;

    CMS_BufferStart = NULL;

    CMS_SetCallBack(NULL);

    CMS_Installed = 0;
}
